// Generated by CoffeeScript 2.1.1
(function() {
  var exports, hideError, showError;

  exports = this;

  showError = function() {
    $('#errorMessage').show();
    $('#password1grp').addClass('has-error');
    $('#password1grp').addClass('has-feedback');
    $('#password2grp').addClass('has-error');
    $('#password2grp').addClass('has-feedback');
  };

  hideError = function() {
    $('#errorMessage').hide();
    $('#password1grp').removeClass('has-error', '');
    $('#password1grp').removeClass('has-feedback', '');
    $('#password2grp').removeClass('has-error', '');
    $('#password2grp').removeClass('has-feedback', '');
  };

  exports.submitForm = function() {
    var pwd1, pwd2;
    pwd1 = $('#newPassword').val();
    pwd2 = $('#confirmation').val();
    if (pwd1.length < 8 || pwd2.length < 8) {
      $('#errorMessage').text('Minimo 8 caratteri.');
      showError();
      return false;
    }
    if (pwd1 === pwd2) {
      console.log('Password validation passed');
      $('#passwordForm').submit();
    } else {
      console.log('Password validation KO');
      showError();
      return false;
    }
  };

  $(function() {
    $('#newPassword').click(function() {
      $('#newPassword').val('');
      $('#confirmation').val('');
      hideError();
    });
    hideError();
  });

  exports = submitForm;

}).call(this);

//# sourceMappingURL=pwdvalidation.js.map
